cmake_minimum_required(VERSION 3.25)
# Shared native build pipeline used by both shell front ends.
get_filename_component(source "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
foreach(name QT_ROOT QPDF_ROOT PDFIUM_ROOT)
  if(NOT DEFINED ${name} OR "${${name}}" STREQUAL "")
    set(${name} "$ENV{${name}}")
  endif()
  if(NOT IS_DIRECTORY "${${name}}")
    message(FATAL_ERROR "Set ${name} to the installed dependency prefix (matching the host compiler/architecture).")
  endif()
  file(TO_CMAKE_PATH "${${name}}" ${name})
endforeach()
if(NOT BUILD_DIR)
  set(BUILD_DIR "${source}/build/release-${CMAKE_HOST_SYSTEM_NAME}")
endif()
if(NOT OUTPUT_DIR)
  set(OUTPUT_DIR "${source}/dist/${CMAKE_HOST_SYSTEM_NAME}")
endif()
get_filename_component(BUILD_DIR "${BUILD_DIR}" ABSOLUTE BASE_DIR "${source}")
get_filename_component(OUTPUT_DIR "${OUTPUT_DIR}" ABSOLUTE BASE_DIR "${source}")
if(NOT GENERATOR)
  set(GENERATOR Ninja)
endif()
if(NOT FORMATS)
  if(CMAKE_HOST_WIN32)
    set(FORMATS ZIP)
  elseif(CMAKE_HOST_APPLE)
    set(FORMATS DMG)
  else()
    set(FORMATS TGZ)
  endif()
endif()
string(REPLACE "," ";" FORMATS "${FORMATS}")
set(generators "")
foreach(format IN LISTS FORMATS)
  string(TOUPPER "${format}" format)
  if(CMAKE_HOST_WIN32 AND format MATCHES "^(ZIP|MSI|EXE)$")
    if(format STREQUAL MSI)
      if(WIX_VERSION STREQUAL "4")
        find_program(wix wix REQUIRED)
      else()
        find_program(candle candle REQUIRED)
        find_program(light light REQUIRED)
      endif()
      list(APPEND generators WIX)
    elseif(format STREQUAL EXE)
      find_program(nsis makensis REQUIRED)
      list(APPEND generators NSIS)
    else()
      list(APPEND generators ZIP)
    endif()
  elseif(CMAKE_HOST_APPLE AND format MATCHES "^(ZIP|TGZ|DMG|PKG)$")
    if(format STREQUAL DMG)
      list(APPEND generators DragNDrop)
    elseif(format STREQUAL PKG)
      list(APPEND generators productbuild)
    else()
      list(APPEND generators "${format}")
    endif()
  elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL Linux AND format MATCHES "^(TGZ|DEB|RPM)$")
    if(format STREQUAL DEB)
      find_program(dpkg_shlibdeps dpkg-shlibdeps REQUIRED)
    elseif(format STREQUAL RPM)
      find_program(rpmbuild rpmbuild REQUIRED)
    endif()
    list(APPEND generators "${format}")
  else()
    message(FATAL_ERROR "Unsupported format '${format}' on ${CMAKE_HOST_SYSTEM_NAME}; build on the target OS.")
  endif()
endforeach()
set(runtime_dirs "${QT_ROOT}/bin;${QPDF_ROOT}/bin;${QPDF_ROOT}/lib;${PDFIUM_ROOT}/bin;${PDFIUM_ROOT}/lib")
if(CMAKE_HOST_WIN32)
  set(ENV{PATH} "${QT_ROOT}/bin;${QPDF_ROOT}/bin;${PDFIUM_ROOT}/bin;$ENV{PATH}")
else()
  set(ENV{PATH} "${QT_ROOT}/bin:$ENV{PATH}")
  if(CMAKE_HOST_APPLE)
    set(ENV{DYLD_LIBRARY_PATH} "${QPDF_ROOT}/lib:${PDFIUM_ROOT}/lib:$ENV{DYLD_LIBRARY_PATH}")
  else()
    set(ENV{LD_LIBRARY_PATH} "${QT_ROOT}/lib:${QPDF_ROOT}/lib:${PDFIUM_ROOT}/lib:$ENV{LD_LIBRARY_PATH}")
  endif()
endif()
function(run)
  execute_process(COMMAND ${ARGV} COMMAND_ERROR_IS_FATAL ANY)
endfunction()
set(extra "")
if(TOOLCHAIN)
  list(APPEND extra "-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN}")
endif()
if(WIX_VERSION)
  list(APPEND extra "-DCPACK_WIX_VERSION=${WIX_VERSION}")
endif()
if(SKIP_TESTS)
  set(testing OFF)
else()
  set(testing ON)
endif()
# Call directly to preserve CMake list-valued arguments as single command arguments.
execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${BUILD_DIR}" -G "${GENERATOR}"
  "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_LIBDIR=lib"
  "-DCMAKE_PREFIX_PATH=${QT_ROOT};${QPDF_ROOT}" "-DPDFIUM_ROOT=${PDFIUM_ROOT}"
  "-DFOLIOFORGE_RUNTIME_DIRS=${runtime_dirs}" "-DFOLIOFORGE_NOTICES_DIR=${NOTICES_DIR}"
  "-DFOLIOFORGE_PACKAGING=ON" "-DFOLIOFORGE_DESKTOP=ON" "-DBUILD_TESTING=${testing}"
  ${extra} COMMAND_ERROR_IS_FATAL ANY)
run("${CMAKE_COMMAND}" --build "${BUILD_DIR}" --config Release --parallel)
get_filename_component(cmake_bin "${CMAKE_COMMAND}" DIRECTORY)
if(NOT SKIP_TESTS)
  if(CMAKE_HOST_WIN32)
    # Test with the same deployed DLLs as the packages, beside the test binaries.
    run("${CMAKE_COMMAND}" --install "${BUILD_DIR}" --config Release --prefix "${BUILD_DIR}/runtime-stage")
    file(GLOB test_runtime "${BUILD_DIR}/runtime-stage/bin/*.dll")
    if(EXISTS "${BUILD_DIR}/Release/engine-tests.exe")
      set(test_bin "${BUILD_DIR}/Release")
    else()
      set(test_bin "${BUILD_DIR}")
    endif()
    file(COPY ${test_runtime} DESTINATION "${test_bin}")
    set(ENV{QT_QPA_PLATFORM_PLUGIN_PATH} "${QT_ROOT}/plugins/platforms")
  endif()
  run("${cmake_bin}/ctest" --test-dir "${BUILD_DIR}" -C Release --output-on-failure --timeout 120)
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")
foreach(generator IN LISTS generators)
  run("${cmake_bin}/cpack" --config "${BUILD_DIR}/CPackConfig.cmake" -C Release -G "${generator}" -B "${OUTPUT_DIR}")
endforeach()
file(GLOB artifacts "${OUTPUT_DIR}/*.zip" "${OUTPUT_DIR}/*.tar.gz" "${OUTPUT_DIR}/*.msi"
  "${OUTPUT_DIR}/*.exe" "${OUTPUT_DIR}/*.deb" "${OUTPUT_DIR}/*.rpm" "${OUTPUT_DIR}/*.dmg" "${OUTPUT_DIR}/*.pkg")
set(checksums "")
foreach(artifact IN LISTS artifacts)
  file(SHA256 "${artifact}" digest)
  get_filename_component(name "${artifact}" NAME)
  string(APPEND checksums "${digest}  ${name}\n")
endforeach()
file(WRITE "${OUTPUT_DIR}/SHA256SUMS" "${checksums}")
message(STATUS "Packages and SHA256SUMS: ${OUTPUT_DIR}")
